# Generated by Django 4.2.2 on 2023-12-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_storycomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycomments',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
