# Generated by Django 4.2.2 on 2023-12-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsstory_options_alter_newsstory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.ImageField(blank=True, height_field='500px', null=True, upload_to='', width_field='500px'),
        ),
    ]
